import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                // Ensure DOM is ready before analytics scripts run
                function ensureDOM() {
                  if (!document.head) {
                    var head = document.createElement('head');
                    document.documentElement.insertBefore(head, document.documentElement.firstChild);
                  }
                  if (!document.body) {
                    var body = document.createElement('body');
                    document.documentElement.appendChild(body);
                  }
                }
                
                if (document.readyState === 'loading') {
                  document.addEventListener('DOMContentLoaded', ensureDOM);
                } else {
                  ensureDOM();
                }
                
                // Patch appendChild to handle null parent gracefully
                if (typeof Element !== 'undefined' && Element.prototype) {
                  var originalAppendChild = Element.prototype.appendChild;
                  Element.prototype.appendChild = function(child) {
                    if (!this) {
                      console.warn('Attempted appendChild on null element');
                      if (document.body) return document.body.appendChild(child);
                      return child;
                    }
                    try {
                      return originalAppendChild.call(this, child);
                    } catch (e) {
                      console.warn('appendChild error:', e);
                      return child;
                    }
                  };
                }
              })();
            `,
          }}
        />
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
